version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  bookingfly:
    build: ./app
    depends_on:
      - mongodb
    ports:
      - 80:3000
    restart: always

volumes:
  mongodb_data:
    driver: local
